services:
  tree-education-webofficialpage:
    container_name: tree-education-webofficialpage
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18082:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - tree-education-network

networks:
  tree-education-network:
    external: true
    name: tree-education-ioas_ioas-network